[project]
name = "agentr"
version = "0.1.0"
description = ""
authors = [
    {name = "jojo"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic (>=0.75.0,<0.76.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "openai (>=2.14.0,<3.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "tavily-python (>=0.7.17,<0.8.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-asyncio (>=1.3.0,<2.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)"
]
